setwd("F:/Github/TopicAnalysis/LinkTopicModel")
library(dplyr)
library(ggplot2)
library(igraph)
library(wordcloud)
# partition Density
PartitionDensity$V1 <- as.numeric(PartitionDensity$V1)
PartitionDensity$V2 <- as.numeric(PartitionDensity$V2)
PartitionDensity$V3 <- 1:nrow(PartitionDensity)
id <- max(which(PartitionDensity$V1==max(PartitionDensity$V1)))
#png('4-1.png', height = 300, width = 500)
g <- ggplot(PartitionDensity,mapping = aes(V2,V1))
g <- g + geom_point()
g <- g + geom_line()
g <- g + geom_line(PartitionDensity2,mapping = aes(V2,V1))
g <- g + geom_line(PartitionDensity3,mapping = aes(V2,V1))
g <- g + geom_line(PartitionDensity4,mapping = aes(V2,V1))
g <- g + geom_line(PartitionDensity5,mapping = aes(V2,V1))
#g <- g + geom_text(data = PartitionDensity[c(399,805,806,807),],mapping = aes(label = V3,sizes=10,hjust=1,vjust=-0.1,fontface=3))
g <- g + labs(x='社区划分数量', y='平均密度')
g
#dev.off()
PartitionDensity5$V1 <- as.numeric(PartitionDensity5$V1)
PartitionDensity5$V2 <- as.numeric(PartitionDensity5$V2)
PartitionDensity5$V3 <- 1:nrow(PartitionDensity5)
