setwd("F:/Github/TopicAnalysis/LinkTopicModel")
library(dplyr)
library(ggplot2)
library(igraph)
library(wordcloud)
# partition Density
PartitionDensity$V1 <- as.numeric(PartitionDensity$V1)
PartitionDensity$V2 <- as.numeric(PartitionDensity$V2)
PartitionDensity$V3 <- 1:nrow(PartitionDensity)
maxid <- max(which(PartitionDensity$V1==max(PartitionDensity$V1)))
PartitionDensity$V2[maxid]
png('4-3.png', height = 800, width = 1000)
g <- ggplot()
g <- g + geom_point(PartitionDensity,mapping = aes(V2,V1,colour="CoNeighborBased LTM"))
g <- g + geom_line(PartitionDensity,mapping = aes(V2,V1,colour="CoNeighborBased LTM"))
g <- g + geom_line(PartitionDensity,mapping = aes(V2[maxid],V1,colour="CoNeighborBased LTM"))
g <- g + geom_text(PartitionDensity,mapping = aes(V2[maxid],V1[maxid],label = paste("密度最优划分","(",V2[maxid],",",V1[maxid],")",sep = ""),vjust = 0,hjust = 0))
g <- g + geom_line(PartitionDensity2,mapping = aes(V2,V1,colour="InsideLinkBased LTM - 0.20 0.05"))
g <- g + geom_line(PartitionDensity4,mapping = aes(V2,V1,colour="InsideLinkBased LTM - 0.35 0.05"))
g <- g + geom_line(PartitionDensity5,mapping = aes(V2,V1,colour="InsideLinkBased LTM - 0.55 0.05"))
g <- g + geom_line(PartitionDensity3,mapping = aes(V2,V1,colour="InsideLinkBased LTM - 0.75 0.05"))
g <- g + geom_line(PartitionDensity6,mapping = aes(V2,V1,colour="InsideLinkBased LTM - 0.55 0.15"))
g <- g + labs(x='社区划分数量', y='平均划分密度',colour = "")
g
dev.off()
PartitionDensity6$V1 <- as.numeric(PartitionDensity6$V1)
PartitionDensity6$V2 <- as.numeric(PartitionDensity6$V2)
PartitionDensity6$V3 <- 1:nrow(PartitionDensity6)

maxid2 <- max(which(PartitionDensity2$V1==max(PartitionDensity2$V1)))

png('4-4.png', height = 800, width = 1000)
g <- ggplot()
g <- g + geom_line(PartitionDensity[1:7500,],mapping = aes(V3,V1,colour="CoNeighborBased LTM"))
g <- g + geom_line(PartitionDensity[1:7500,],mapping = aes(V3[maxid],V1,fill="black"))
g <- g + geom_text(PartitionDensity,mapping = aes(V3[maxid],0,label = V3[maxid],vjust = 0,hjust = 0))
g <- g + geom_line(PartitionDensity2,mapping = aes(V3,V1,colour="InsideLinkBased LTM - 0.20 0.05"))
g <- g + geom_line(PartitionDensity2,mapping = aes(V3[maxid2],V1,fill="black"))
g <- g + geom_text(PartitionDensity2,mapping = aes(V3[maxid2],0,label = V3[maxid2],vjust = 0,hjust = 0))
g <- g + geom_line(PartitionDensity4,mapping = aes(V3,V1,colour="InsideLinkBased LTM - 0.35 0.05"))
g <- g + geom_line(PartitionDensity5,mapping = aes(V3,V1,colour="InsideLinkBased LTM - 0.55 0.05"))
g <- g + geom_line(PartitionDensity3,mapping = aes(V3,V1,colour="InsideLinkBased LTM - 0.75 0.05"))
g <- g + geom_line(PartitionDensity6,mapping = aes(V3,V1,colour="InsideLinkBased LTM - 0.55 0.15"))
g <- g + labs(x='合并次数', y='平均划分密度',colour = "")
g
dev.off()
